/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\yuanlin\\www\\yylAdminDoc\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4bb08f28",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bb08f28").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-df3da168",
    path: "/course/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df3da168").then(next)
    },
  },
  {
    path: "/course/index.html",
    redirect: "/course/"
  },
  {
    name: "v-00e97928",
    path: "/fqa/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00e97928").then(next)
    },
  },
  {
    path: "/fqa/index.html",
    redirect: "/fqa/"
  },
  {
    name: "v-0c2b896e",
    path: "/guide/base/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c2b896e").then(next)
    },
  },
  {
    path: "/guide/base/index.html",
    redirect: "/guide/base/"
  },
  {
    path: "/guide/base.html",
    redirect: "/guide/base/"
  },
  {
    name: "v-5ce5ce36",
    path: "/guide/catalog/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ce5ce36").then(next)
    },
  },
  {
    path: "/guide/catalog/index.html",
    redirect: "/guide/catalog/"
  },
  {
    path: "/guide/catalog.html",
    redirect: "/guide/catalog/"
  },
  {
    name: "v-7c744ca5",
    path: "/guide/install/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c744ca5").then(next)
    },
  },
  {
    path: "/guide/install/index.html",
    redirect: "/guide/install/"
  },
  {
    path: "/guide/install.html",
    redirect: "/guide/install/"
  },
  {
    name: "v-a9d0cac8",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a9d0cac8").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-5d2043f6",
    path: "/guide/thank/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d2043f6").then(next)
    },
  },
  {
    path: "/guide/thank/index.html",
    redirect: "/guide/thank/"
  },
  {
    path: "/guide/thank.html",
    redirect: "/guide/thank/"
  },
  {
    name: "v-0b1366ee",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b1366ee").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-8d83ac2a",
    path: "/use/adminapi/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8d83ac2a").then(next)
    },
  },
  {
    path: "/use/adminapi/index.html",
    redirect: "/use/adminapi/"
  },
  {
    path: "/use/adminapi.html",
    redirect: "/use/adminapi/"
  },
  {
    name: "v-549463b6",
    path: "/use/adminpage/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-549463b6").then(next)
    },
  },
  {
    path: "/use/adminpage/index.html",
    redirect: "/use/adminpage/"
  },
  {
    path: "/use/adminpage.html",
    redirect: "/use/adminpage/"
  },
  {
    name: "v-d5833076",
    path: "/use/apidoc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d5833076").then(next)
    },
  },
  {
    path: "/use/apidoc/index.html",
    redirect: "/use/apidoc/"
  },
  {
    path: "/use/apidoc.html",
    redirect: "/use/apidoc/"
  },
  {
    name: "v-0910a8f1",
    path: "/use/indexapi/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0910a8f1").then(next)
    },
  },
  {
    path: "/use/indexapi/index.html",
    redirect: "/use/indexapi/"
  },
  {
    path: "/use/indexapi.html",
    redirect: "/use/indexapi/"
  },
  {
    name: "v-a5d073f4",
    path: "/use/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a5d073f4").then(next)
    },
  },
  {
    path: "/use/index.html",
    redirect: "/use/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]